#ifndef ARCGEOSIM_MESH_MESHTYPES_H_
#define ARCGEOSIM_MESH_MESHTYPES_H_

#include "ArcGeoSim/Utils/ArcGeoSim.h"


BEGIN_ARCGEOSIM_NAMESPACE
BEGIN_MESH_NAMESPACE

template<typename ItemType>
struct ItemTraits {} ;

END_MESH_NAMESPACE
END_ARCGEOSIM_NAMESPACE


#endif /*MESHTYPES_H_*/
