// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2022 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
// -*- C++ -*-
#ifndef ARCGEOSIM_MESH_UTILS_STRINGTOITEMUTILS_H
#define ARCGEOSIM_MESH_UTILS_STRINGTOITEMUTILS_H
/* Author : dechaiss at Thu Oct 14 15:41:55 2010
 * Generated by createNew
 */

#include <arcane/ArcaneTypes.h>
#include "ArcGeoSim/Utils/ArcGeoSim.h"

BEGIN_ARCGEOSIM_NAMESPACE

class StringToItemUtils
{
public:
  
  /** Constructeur de la classe */
  StringToItemUtils() {}
  
  /** Destructeur de la classe */
  virtual ~StringToItemUtils() {}
  
public:

  /** String to item type conversion */
  static Arcane::Integer stringToItemType(const Arcane::String & string);

  /** String to item kind conversion */
  static Arcane::eItemKind stringToItemKind(const Arcane::String & string);

  /** Item kind to String conversion */
  static Arcane::String itemKindToString(const Arcane::eItemKind & item_kind);

};

END_ARCGEOSIM_NAMESPACE

#endif /* ARCGEOSIM_MESH_UTILS_STRINGTOITEMUTILS_H */
