// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2022 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
#ifndef GROUPCREATOR_IGROUPCREATOR_H
#define GROUPCREATOR_IGROUPCREATOR_H
/* Author : haeberlf at Fri Feb 20 10:59:31 2009
 * Generated by createNew
 */

namespace Arcane {}
using namespace Arcane;

class IGroupCreator
{
public:

  IGroupCreator() {}
  
  virtual ~IGroupCreator() { }
  
public:

  //! Initialisation
  virtual void init() = 0;

  //! Geometric properties
  virtual void prepare() = 0;

  //! Apply service function
  virtual void apply() = 0;
};

#endif /* GROUPCREATOR_IGROUPCREATOR_H */
