// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2022 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
// -*- C++ -*-
#ifndef ARCGEOSIM_MESH_GEOMETRY_NOOPTIMIZATIONGEOMETRYPOLICY_H
#define ARCGEOSIM_MESH_GEOMETRY_NOOPTIMIZATIONGEOMETRYPOLICY_H
/* Author : havep at Thu Aug 18 09:25:29 2011
 * Generated by createNew
 */

#include "ArcGeoSim/Mesh/Geometry/IGeometryPolicy.h"

class NoOptimizationGeometryPolicy
  : public IGeometryPolicy
{
public:
  /** Constructeur de la classe */
  NoOptimizationGeometryPolicy() {}
  
  /** Destructeur de la classe */
  virtual ~NoOptimizationGeometryPolicy() {}
  
public:
  Arcane::Int64 context() { return -1; }

  void beginContext() { }

  void endContext() { }
};

#endif /* ARCGEOSIM_MESH_GEOMETRY_NOOPTIMIZATIONGEOMETRYPOLICY_H */
