// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2025 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
#ifndef ARCGEOSIM_NUMERICS_NONLINEARSOLVER_INONLINEARSYSTEM_H
#define ARCGEOSIM_NUMERICS_NONLINEARSOLVER_INONLINEARSYSTEM_H
/* Author : desrozis at Fri Mar 27 12:11:29 2009
 * Generated by createNew
 */

#include <arcane/utils/ArcaneGlobal.h>

#ifdef USE_ALIEN_ARCGEOSIM
#include "ArcGeoSim/Numerics/LinearAlgebra2/LinearAlgebra2.h"
#endif
#ifdef USE_ALIEN_V0
#include <ALIEN/BaseObjects/Matrix.h>
#include <ALIEN/BaseObjects/Vector.h>
#endif
#ifdef USE_ALIEN_V1
#include <ALIEN/Alien-IFPEN.h>
#endif
#ifdef USE_ALIEN_V2
#include <alien/ref/AlienRefSemantic.h>
#include <alien/arcane_tools/IIndexManager.h>
#include <alien/arcane_tools/indexManager/BasicIndexManager.h>
#include <alien/arcane_tools/indexManager/SimpleAbstractFamily.h>
#include <alien/arcane_tools/distribution/DistributionFabric.h>
#include <alien/arcane_tools/indexSet/IndexSetFabric.h>
#include <alien/arcane_tools/data/Space.h>
#include <alien/arcane_tools/distribution/DistributionFabric.h>
#include <alien/arcane_tools/indexSet/IndexSetFabric.h>
#include <alien/expression/solver/ILinearSolver.h>
#endif

#ifdef USE_ALIEN_V1
#include <ALIEN/Alien-IFPEN.h>
#include "ALIEN/Externals/IndexManager/BasicIndexManager.h"
#endif



using namespace Arcane;

class INonLinearSystemVisitor;
class ILinearSystem ;

class INonLinearSystem
{
public:
  /** Constructeur de la classe */
  INonLinearSystem()
    {
      ;
    }

  /** Destructeur de la classe */
  virtual ~INonLinearSystem() { }

public:

  //! Initialisation
  virtual void init() = 0;

  //! Initializing the system
  virtual void start() = 0 ;

  //! Finalizing the system
  virtual void end() = 0 ;

  virtual void allocateData() = 0 ;
  virtual void freeData() = 0 ;

  //! Computing at the begin of the iterative step
  virtual void startStep() = 0 ;

  //! Computing at the end of the iterative step
  virtual void endStep() = 0 ;

  //! Visitor pattern
  virtual Integer accept(INonLinearSystemVisitor* visitor) = 0 ;

  //! Getting linear system
  virtual ILinearSystem * getLinearSystem() {
    return NULL ;
  }
#ifdef USE_ALIEN_V2
  typedef Alien::IMatrix                        MatrixType;
  typedef Alien::IVector                        VectorType;
  typedef Alien::ArcaneTools::BasicIndexManager IndexManagerType;
  typedef Alien::ArcaneTools::Space             SpaceType ;

#endif
#ifdef USE_ALIEN_V1
  typedef Alien::IMatrix                      MatrixType;
  typedef Alien::IVector                      VectorType;
  typedef Alien::Externals::BasicIndexManager IndexManagerType;
  typedef Alien::Space                        SpaceType ;
#endif
#ifdef USE_ALIEN_V0
  typedef Alien::Matrix MatrixType ;
  typedef Alien::Vector VectorType ;
  typedef Alien::IIndexManager*           IndexManagerType;
  typedef Alien::Space                    SpaceType ;
#endif

  virtual MatrixType const& getMatrix() const = 0 ;
  virtual VectorType const& getRHS() const = 0 ;
  virtual VectorType const& getSolution() const = 0 ;
  virtual VectorType&       getSolution() = 0 ;

  virtual void initLinearSystem() = 0 ;

  //A. Anciaux pour BlockTailleVariable
  virtual void initLinearSystem(bool rs_block) = 0 ; 

  virtual void buildLinearSystem() = 0 ;
  virtual Integer updateLinearSolution() = 0 ;
};

#endif /* ARCGEOSIM_NUMERICS_NONLINEARSOLVER_INONLINEARSYSTEM_H */
