// -*- C++ -*-
/* Author : dipietrd at Wed Jun 22 14:17:40 2011
 * Generated by createNew
 */

/* INFO: Les services et modules se conforment maintenant à la politique Arcane core.
 *       L'emploi des .h était fictif. 
 *       Désormais les déclarations de classe pour les modules et services seront
 *       localisées dans le fichier .cc correspondant.
 */

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#include <arcane/IMeshSubMeshTransition.h>
#include <arcane/SharedVariable.h>
#include <arcane/IItemFamily.h>
using namespace Arcane;

// Interface du service 
#include "ArcGeoSim/Mesh/Geometry/IGeometry.h"
#include "ArcGeoSim/Mesh/Geometry/IGeometryMng.h"
#include "ArcGeoSim/Mesh/Geometry/Euclidian/EuclidianGeometry.h"
#include "EuclidianGeometry2_axl.h"
#include "ArcGeoSim/Mesh/Geometry/Impl/GeometryServiceBase.h"

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

class EuclidianGeometry2Service 
  : public ArcaneEuclidianGeometry2Object
  , public GeometryServiceBase
{
public:
  
  /** Constructeur de la classe */
  EuclidianGeometry2Service(const Arcane::ServiceBuildInfo & sbi) 
    : ArcaneEuclidianGeometry2Object(sbi)
    , GeometryServiceBase()
    , m_initialized(false)
  {
    ;
  }
  
  /** Destructeur de la classe */
  ~EuclidianGeometry2Service() 
  {
    for(SharedGeometryMap::iterator i = m_shared_geometry.begin(); i != m_shared_geometry.end(); ++i)
      {
        delete i->second.first; // SharedEuclidianGeometry2
        delete i->second.second; // SharedMeshVariableScalarRefT<Node,Real3>
      }

    for(UniqGeometryMap::iterator i = m_uniq_geometry.begin(); i != m_uniq_geometry.end(); ++i)
      {
        delete i->second; // EuclidianGeometry2
      }
  }

  
public:
  //! Initialisation
  void init();

  //@{ @name property management by group

  //! Update property values for an ItemGroup
  void update(ItemGroup group);

  //! Reset property for an ItemGroup
  void reset(ItemGroup group);
  
  //@}

  //! Get underlying geometry
  IGeometry * geometry(IMesh * mesh = NULL);

  //! Get dimension associated to this geometry mng
  Dimension dimension() const { return Dimension::e2Dyz; }

  //! Remove geometry reference to a given mesh
  /*! Used for deleted sub-meshes */
  void unregisterMesh(IMesh * mesh);

public:
  //@{ Extended interface for GeometryServiceBase

  //! Access to traceMng
  ITraceMng * traceMng() { return ArcaneEuclidianGeometry2Object::traceMng(); }

  //! Access to Mesh
  IMesh * mesh() { return ArcaneEuclidianGeometry2Object::subDomain()->defaultMesh(); }

  //! Name of instancied class
  const char * className() const { return "Euclidian2Geometry"; }

  //@}

private:
  //! Shared geometry builder
  EuclidianGeometry::SharedEuclidianGeometry2 * sharedGeometry(IMesh * mesh);
  //! Uniq geometry builder
  EuclidianGeometry::EuclidianGeometry2 * uniqGeometry(IMesh * mesh);

private: 
  bool m_initialized;

  typedef std::map<IMesh*,
                   std::pair<EuclidianGeometry::SharedEuclidianGeometry2*, 
                             SharedMeshVariableScalarRefT<Node,Real3>* > > SharedGeometryMap;
  typedef std::map<IMesh*,EuclidianGeometry::EuclidianGeometry2*> UniqGeometryMap;
  SharedGeometryMap m_shared_geometry;  
  UniqGeometryMap m_uniq_geometry;
};

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

void EuclidianGeometry2Service::init()
{
  if (m_initialized)
    {
      info() << className() << " already initialized";
      return;
    }

  if (options()->variableSuffix.size() > 0)
    {
      setSuffix(options()->variableSuffix[0]);
    }
  else
    {
      setSuffix(String());
    }

  m_initialized = true;
}

/*---------------------------------------------------------------------------*/

void EuclidianGeometry2Service::update(ItemGroup group)
{
  IMesh * mesh = group.mesh();
  const bool isUniqMesh = (mesh->parentMesh() == NULL);
  
  if (isUniqMesh)
    updateGroup(group,*uniqGeometry(mesh));
  else
    updateGroup(group,*sharedGeometry(mesh));
}

/*---------------------------------------------------------------------------*/

void EuclidianGeometry2Service::reset(ItemGroup group)
{
  // Do nothing
}

/*---------------------------------------------------------------------------*/

EuclidianGeometry::EuclidianGeometry2 *
EuclidianGeometry2Service::
uniqGeometry(IMesh * mesh)
{
  UniqGeometryMap::iterator finder = m_uniq_geometry.find(mesh);
  if (finder == m_uniq_geometry.end()) 
    { // Build new shared geometry
      UniqGeometryMap::mapped_type & mapped = m_uniq_geometry[mesh];
      // L'implémentation actuelle se construit sur le maillage par défaut
      mapped = new EuclidianGeometry::EuclidianGeometry2(PRIMARYMESH_CAST(mesh)->nodesCoordinates(), traceMng(), options()->fatalOnError());
      return mapped;
    }
  else
    {
      return finder->second;
    }
}

/*---------------------------------------------------------------------------*/

EuclidianGeometry::SharedEuclidianGeometry2 *
EuclidianGeometry2Service::
sharedGeometry(IMesh * mesh)
{
  SharedGeometryMap::iterator finder = m_shared_geometry.find(mesh);
  if (finder == m_shared_geometry.end()) 
    { // Build new shared geometry
      SharedGeometryMap::mapped_type & mapped = m_shared_geometry[mesh];
      mapped.second = new SharedMeshVariableScalarRefT<Node,Real3>(mesh->nodeFamily(),
                                                                   PRIMARYMESH_CAST(this->mesh())->nodesCoordinates());
      mapped.first = new EuclidianGeometry::SharedEuclidianGeometry2(*mapped.second, traceMng(), options()->fatalOnError());
      return mapped.first;
    }
  else
    {
      return finder->second.first;
    }
}
 
/*---------------------------------------------------------------------------*/

IGeometry * EuclidianGeometry2Service::geometry(IMesh * mesh)
{
  // Utilise le maillage par défaut si aucun maillage n'est fourni
  if (mesh == NULL) mesh = this->mesh();

  const bool isUniqMesh = (mesh->parentMesh() == NULL);

  if (isUniqMesh)
    return uniqGeometry(mesh);
  else
    return sharedGeometry(mesh);
}

/*---------------------------------------------------------------------------*/

void EuclidianGeometry2Service::unregisterMesh(IMesh * mesh)
{
  if (mesh == NULL) mesh = this->mesh();
  GeometryServiceBase::unregisterMesh(m_uniq_geometry, m_shared_geometry, mesh);
}

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

using namespace Arcane;
ARCANE_REGISTER_SERVICE_EUCLIDIANGEOMETRY2(EuclidianGeometry2,EuclidianGeometry2Service);
