#ifndef ARCGEOSIM_TESTS_SERVICETESTERS_OBSERVABLEPROPERTYTESTER_OBSERVABLEPROPERTYTESTERSERVICE_H
#define ARCGEOSIM_TESTS_SERVICETESTERS_OBSERVABLEPROPERTYTESTER_OBSERVABLEPROPERTYTESTERSERVICE_H
/* Author : dipietrd at Wed Aug  6 11:29:08 2008
 * Generated by createNew
 */

#include "Tests/ServiceTesters/IServiceTester.h"
#include "Utils/ObservableProperty.h"

namespace Arcane { }
using namespace Arcane;

#include "ObservablePropertyTester_axl.h"

/*--------------------------------------------------------*/

class ObservablePropertyTesterService :
public ArcaneObservablePropertyTesterObject
{
 public:
  /** Constructeur de la classe */
  ObservablePropertyTesterService(const Arcane::ServiceBuildInfo & sbi) : 
    ArcaneObservablePropertyTesterObject(sbi) 
    {
      ;
    }
  
  /** Destructeur de la classe */
  virtual ~ObservablePropertyTesterService() {}
  
 public:

  //! Action 2
  void action2();

 public:
  //! Initialization
  void init();
  //! Run the test
  int test();
};

#endif /* ARCGEOSIM_TESTS_SERVICETESTERS_OBSERVABLEPROPERTYTESTER_OBSERVABLEPROPERTYTESTERSERVICE_H */
