// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2022 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
// -*- C++ -*-
#ifndef ARCGEOSIM_ARCGEOSIM_MESH_UTILS_IXMTOOLS_HDFREADER_H
#define ARCGEOSIM_ARCGEOSIM_MESH_UTILS_IXMTOOLS_HDFREADER_H
/* Author : dechaiss at Tue Nov  6 11:11:36 2012
 * Generated by createNew
 */

#include "ArcGeoSim/Utils/ArcGeoSim.h"

BEGIN_ARCGEOSIM_NAMESPACE

/*!
 * Lecture d'un tableau dans un fichier Hdf5. Cette fonction permet de manipuler
 * simplement les outils hdf5 et en ayant mis les include hdf arcane dans le .cc
 * ce qui evite d'etre contamine par des "use hdf" et "use mpi" partout.
 */

namespace HdfReader
{

template <typename DataType>
void read(Arcane::Array<DataType>& data, const Arcane::String& filename,const String& file_position);

}

END_ARCGEOSIM_NAMESPACE

#endif /* ARCGEOSIM_ARCGEOSIM_MESH_UTILS_IXMTOOLS_HDFREADER_H */
