// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2022 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
// -*- C++ -*-
#ifndef ARCGEOSIM_UTILS_MAKEDELEGATEDSHAREDPTR_H
#define ARCGEOSIM_UTILS_MAKEDELEGATEDSHAREDPTR_H
/* Author : desrozis at Wed Nov 16 11:59:36 2016
 * Generated by createNew
 */

#include <memory>

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

namespace ArcGeoSim {

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

template<typename T>
std::shared_ptr<T> makeDelegatedSharedPtr(T* t)
{
  return std::shared_ptr<T>(t, [](T*) {});
}

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

}

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#endif /* ARCGEOSIM_UTILS_MAKEDELEGATEDSHAREDPTR_H */
