// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2025 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
// -*- C++ -*-
#ifndef ARCGEOSIM_ARCGEOSIM_UTILS_OPTIONAL_H
#define ARCGEOSIM_ARCGEOSIM_UTILS_OPTIONAL_H
/* Author : desrozis at Mon Oct 27 10:41:43 2014
 * Generated by createNew
 */

#include "ArcGeoSim/Utils/ArcGeoSim.h"

#include <arcane/CaseOptions.h>

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

BEGIN_ARCGEOSIM_NAMESPACE

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

template<typename T>
class Optional
{
public:
  
  Optional() 
    : m_is_setted(false)
    , m_value(T(0)) {}
  
  Optional(const Optional<T>& o)
    : m_is_setted(o.m_is_setted)
    , m_value(o.m_value) {}

  Optional(T value)
    : m_is_setted(true)
    , m_value(value) {}

  Optional(const Arcane::CaseOptionSimpleT<T>& value)
    : m_is_setted(false)
    , m_value(T(0))
  {
    if(not value.hasValidValue()) return;
    m_is_setted = true;
    m_value = value();
  }

  bool null() const { return m_is_setted == false; }

  Optional<T>& operator=(const Arcane::CaseOptionSimpleT<T>& value)
  {
    if(value.hasValidValue()) {
      m_is_setted = true;
      m_value = value();
    }
    return *this;
  }

  Optional<T>& operator=(T value) 
  {
    m_is_setted = true;
    m_value = value;
    return *this;
  }

  T operator()() const 
  { 
    if(null()) 
      throw Arcane::FatalErrorException("Optional is null");
    return m_value; 
  }
  
public:

  bool m_is_setted;

  T m_value;
};

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

END_ARCGEOSIM_NAMESPACE;

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#endif /* ARCGEOSIM_ARCGEOSIM_UTILS_OPTIONAL_H */
