#ifndef ARCGEOSIM_NUMERICS_LINEARSOLVER_MTLSOLVERIMPL_MTLINTERNAL_H
#define ARCGEOSIM_NUMERICS_LINEARSOLVER_MTLSOLVERIMPL_MTLINTERNAL_H
/* Author : havep at Fri Jun  6 17:56:23 2008
 * Generated by createNew
 */

//! Internal struct for MTL implementation
/*! Separate data from header; 
 *  can be only included by LinearSystem and LinearSolver
 */

namespace {
#include <boost/numeric/linear_algebra/inverse.hpp>
#include <boost/numeric/mtl/mtl.hpp>
#include <boost/numeric/itl/itl.hpp>
}

struct MTLInternal 
{
  typedef mtl::matrix::parameters<mtl::row_major, mtl::index::c_index, mtl::non_fixed::dimensions, false, unsigned> row_para;
  typedef mtl::matrix::parameters<mtl::tag::col_major> col_para;
  typedef mtl::compressed2D<double,col_para> col_matrix_type;
  typedef mtl::compressed2D<double,row_para> row_matrix_type;
  typedef mtl::compressed2D<double,row_para> matrix_type;
  typedef mtl::dense_vector<double>  vector_type;
#ifdef USE_PMTL4
  typedef mtl::matrix::distributed< matrix_type >  MTLMatrix;
  typedef mtl::vector::distributed< vector_type >  MTLVector;
#else
  typedef row_matrix_type                          MTLMatrix ;
  typedef vector_type                              MTLVector ;
#endif

  MTLMatrix* m_matrix;
  MTLVector* m_x ;
  MTLVector* m_rhs ;

  int        m_row_offset ;
};

#endif /* ARCGEOSIM_NUMERICS_LINEARSOLVER_HYPRESOLVERIMPL_HYPREINTERNAL_H */
