// -*- C++ -*-
/* Author : havep at Tue May  2 09:55:27 2017
 * Generated by createNew
 */

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#include "ArcGeoSim/Tests/Utils/IDataAccessor.h"
#include <arcane/IVariable.h>

struct ReducedArrayVariableAccessorTypes
{
    enum eReduction
    {
        Min, Max, Mean, Sum
    };
};

#include "ReducedArrayVariableAccessor_axl.h"

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

class ReducedArrayVariableAccessorService 
  : public ArcaneReducedArrayVariableAccessorObject
{
public:
  
  /** Constructeur de la classe */
  ReducedArrayVariableAccessorService(const Arcane::ServiceBuildInfo & sbi);
  
  /** Destructeur de la classe */
  ~ReducedArrayVariableAccessorService() {}
  
public:

  //! Initialisation
  void init(const ItemGroup& group);

  //! Apply service function
  IVariable* variable(const ItemGroup& group);


private:
  // initialization flag
  bool m_initialized;

  //! Variable data
  IVariable * m_ivariable;

private:
  template<typename T> Real computeReduction(const ConstArrayView<T> & data);
};

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#include <arcane/IVariableMng.h>
#include <arcane/IMesh.h>
#include <arcane/IItemFamily.h>
#include <arcane/ArcaneVersion.h>
#include "ArcGeoSim/Mesh/Utils/VariableUtils.h"

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

ReducedArrayVariableAccessorService::
ReducedArrayVariableAccessorService(const Arcane::ServiceBuildInfo & sbi)
  : ArcaneReducedArrayVariableAccessorObject(sbi)
  , m_initialized(false)
  , m_ivariable(nullptr)
{
  ;
}

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

void
ReducedArrayVariableAccessorService::
init(const ItemGroup& group)
{
  if (m_initialized)
    return;

  //! Variable manager
  IVariableMng * variable_mng = subDomain()->variableMng();

  //! Variable name
  String variable_name = options()->name();

  //! Find variable
  m_ivariable = variable_mng->findMeshVariable(mesh(), variable_name);

  //! Check compatibility
  if (m_ivariable == NULL)
  {
    fatal() << "Variable '" << variable_name << "' not defined";
  }

  // Data type => Real
  if (m_ivariable->dataType() != DT_Real)
  {
    fatal() << "Variable '" << variable_name
            << "' data type not REAL (actually only used)";
  }

  // Data type => Real
  if (m_ivariable->itemGroup().null())
  {
    fatal() << "Variable '" << variable_name
            << "' item-group is not defined";
  }

  // Data type => Real
  if (m_ivariable->dimension() != 2)
  {
    fatal() << "Variable '" << variable_name
            << "' is not an mesh array variable";
  }

  //! Check group compatibility
  if (group.itemKind() != m_ivariable->itemKind())
    fatal() << "Incompatible kind between " << m_ivariable->name()
            << " variable and " << group.name() << " group";

  m_initialized = true;
}

/*---------------------------------------------------------------------------*/

IVariable*
ReducedArrayVariableAccessorService::
variable(const ItemGroup& group)
{
  if (!m_initialized)
  {
    fatal() << "Service not initialized";
  }

  // Check if variable is used, if not reconstruct it
  if (!m_ivariable->isUsed())
  {
    m_ivariable->setUsed(true);
    if (m_ivariable->computeFunction()) m_ivariable->computeFunction()->execute();
  }// Warning variable stay in used state

  //! Build reduced variable
  String name = String::concat(options()->name(),options()->reduction());

  IVariable* result_variable = ArcGeoSim::VariableUtils::createMeshVariable(name,
                                                                            m_ivariable->dataType(),
                                                                            m_ivariable->itemKind(),1,
                                                                            m_ivariable->isPartial(),
                                                                            m_ivariable->itemGroup(),
                                                                            m_ivariable->property());
  const ItemVariableArrayRefT<Real> var(m_ivariable);
  ItemVariableScalarRefT<Real> result(result_variable);

  ENUMERATE_ITEM(item, group) {
    result[item] = computeReduction(var[item]);
  }

  return result_variable;
}

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

template<typename T>
Real
ReducedArrayVariableAccessorService::
computeReduction(const ConstArrayView<T> & data)
{
  Real value = 0;
  switch (options()->reduction())
  {
    case ReducedArrayVariableAccessorTypes::Min:
    {
      value = +FloatInfo<Real>::maxValue();
      for(auto v : data)
        value = math::min(value,(Real) v);
    }
      break;
    case ReducedArrayVariableAccessorTypes::Max:
    {
      value = -FloatInfo<Real>::maxValue();
      for(auto v : data)
        value = math::max(value,(Real) v);
    }
      break;
    case ReducedArrayVariableAccessorTypes::Mean:
    {
      for(auto v : data)
        value += (Real)v;
      value /= data.size();
    }
      break;
    case ReducedArrayVariableAccessorTypes::Sum:
    {
      for(auto v : data)
        value += (Real)v;
    }
      break;
    default:
      error() << "Undefined reduction type [" << options()->reduction() << "]";
  }
  return value;
}

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

using namespace Arcane;
ARCANE_REGISTER_SERVICE_REDUCEDARRAYVARIABLEACCESSOR(ReducedArrayVariableAccessor,ReducedArrayVariableAccessorService);

