// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2022 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
#ifndef ARCANEDEMO_DIPHASICTEST_WELL_IWELL_H
#define ARCANEDEMO_DIPHASICTEST_WELL_IWELL_H
/* Author : desrozis at Tue May 24 10:05:16 2011
 * Generated by createNew
 */

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#include "ArcGeoSim/Utils/ItemGroupMap.h"

#include <arcane/VariableTypedef.h>

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

enum eWellType {
    WT_Injector,
    WT_Productor
};

class IWell
{
public:
  virtual ~IWell() {}
public:
  //! Initialisation
  virtual void init(const Arcane::VariableCellReal& permeability,
                    const Arcane::VariableNodeReal3& node_coordinates,
                    const bool useDefaultFormula=true) = 0;

  // Donne les mailles perforees
  virtual Arcane::CellGroup perforatedCells() const = 0;

  // Donne les mailles parentes
  virtual Arcane::CellGroup parentCells() const = 0;

  // Type de puits
  virtual eWellType type() const = 0;

  // Mise a jour des cellules perforees pour l'AMR
  virtual void update_PerforatedCells_After_Refinement(const Arcane::CellGroup & old_pc ) = 0;

  virtual void update_PerforatedCells_After_Coarsening(const Arcane::CellGroup & old_parents ) = 0;

  // Recalcul de l'indice de productivite si le maillage a change
  virtual void reinit(const Arcane::VariableCellReal& permeability,
                      const Arcane::VariableNodeReal3& node_coordinates,
                      const bool useDefaultFormula=true) = 0;

  // Donne l'indice de productivite
  virtual const ItemGroupMapT<Cell,Real>& productivityIndex() const = 0;

  // Donne la pression du puits
  virtual Arcane::Real pressure() const = 0;

  virtual Arcane::Real refZ() const = 0;

};

#endif /* ARCANEDEMO_DIPHASICTEST_WELL_IWELL_H */
