#ifndef ARCGEOSIM_NUMERICS_LINEARSOLVER_SLUSOLVERIMPL_SLUINTERNAL_H
#define ARCGEOSIM_NUMERICS_LINEARSOLVER_SLUSOLVERIMPL_SLUINTERNAL_H
/* Author : havep at Fri Jun  6 17:56:23 2008
 * Generated by createNew
 */

//! Internal struct for SLU implementation
/*! Separate data from header; 
 *  can be only included by LinearSystem and LinearSolver
 */


#include "slu_ddefs.h"

class SuperLUInternal
{
public :
  SuperLUInternal(Integer nrow,Integer ncol,const Arcane::ConstArrayView<Integer> & lineSizes)
  : m_nrow(nrow)
  , m_ncol(ncol)
  {
    if ( !(m_xa = intMalloc(nrow+1)) ) ABORT("Malloc fails for xa[].");
    m_xa[0] = 0 ;
    for(Integer irow=0;irow<nrow;++irow)
    {
      m_xa[irow+1] = m_xa[irow] + lineSizes[irow] ;
    }
    m_nnz = m_xa[nrow] ;

    m_x.resize(nrow) ;
    if ( !(m_a = doubleMalloc(m_nnz)) ) ABORT("Malloc fails for a[].");
    if ( !(m_asub = intMalloc(m_nnz)) ) ABORT("Malloc fails for asub[].");
    if ( !(m_rhs = doubleMalloc(nrow)) ) ABORT("Malloc fails for rhs[].");
  }
  virtual ~SuperLUInternal()
  {
    SUPERLU_FREE (m_rhs);
    Destroy_CompRow_Matrix(&m_A);
    Destroy_SuperMatrix_Store(&m_B);
  }

  SuperMatrix m_A ;
  SuperMatrix m_L ;
  SuperMatrix m_U ;
  SuperMatrix m_B ;
  SuperMatrix m_X ;

  double*     m_a ;
  SharedArray<Real> m_x ;
  double*     m_rhs ;
  int*        m_asub ;
  int*        m_xa ;
  Integer     m_nrow ;
  Integer     m_ncol ;
  Integer     m_nnz ;
};

#endif /* ARCGEOSIM_NUMERICS_LINEARSOLVER_HYPRESOLVERIMPL_HYPREINTERNAL_H */
