#include "ArcGeoSim/Utils/Utils.h"
#include "ArcGeoSim/Appli/IAppServiceMng.h"
#include <arcane/IParallelMng.h>
#include "arcane/std/MeshPartitionerBase.h"
#include "ArcGeoSim/Mesh/Geometry/IGeometryMng.h"


#include "IfpMeshPartitionerTesterService.h"

/* Author : mesriy at Thu jan 27 14:05:59 2009
 * Generated by createNew
 */

using namespace Arcane;

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

void IfpMeshPartitionerTesterService::init() {
  
}

/*---------------------------------------------------------------------------*/

int IfpMeshPartitionerTesterService::test() {
	// partition the mesh
	info() << "Partitioning mesh using IFP library:";
	CellGroup own_cells=mesh()->ownCells();
	NodeGroup own_nodes=mesh()->ownNodes();
	Integer nb_own_cell = own_cells.size();
	info() << " nb_own_cell=" << nb_own_cell;
	info() << " nb_all_cell=" << allCells().size();
	info() << " nb_all_node=" << allNodes().size(); 
	 
	Integer domain_id = subDomain()->subDomainId() ;
	ENUMERATE_CELL(icell,ownCells())
	{
		m_cell_owner[icell] = domain_id ;
	}
	/** paraview n'arrive pas a afficher correctement node_owner
	 * le format lu est ensight
	 * apparement un probleme de visualisation des entites de type <node>
	 */
	ENUMERATE_NODE(inode,own_nodes)
		{
			m_node_owner[inode] = domain_id ;
			/*if(domain_id == 1){
				pinfo() << "JE SUIS LE PROC 1>>>>>>>>>>>>>>>>>>>>>>>>>>>"
						<<  m_node_owner[inode];
			}*/
		}
	//partitioner->partitionMesh(false);
	 
	  
  return 1 ;
}

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

ARCANE_REGISTER_SERVICE_IFPMESHPARTITIONERTESTER(IfpMeshPartitionerTester,IfpMeshPartitionerTesterService);

