/* Author : havep at Fri Jul  4 09:15:48 2008
 * Generated by createNew
 */

#include "ArcGeoSim/Numerics/LinearAlgebra2/PETScImpl/PETScPrecomp.h"
#include "ArcGeoSim/Numerics/LinearSolver/PETScSolverImpl/IPETScPC.h"
#include "ArcGeoSim/Numerics/LinearSolver/PETScSolverImpl/IPETScKSP.h"

struct PETScPrecConfigAdditiveSchwarzOptionTypes 
{
  enum eType 
    {
      Basic,
      Restrict,
      Interpolate,
      None
    };
};

using namespace Arcane;
using namespace ArcGeoSim::Numerics;
#include "PETScPrecConfigAdditiveSchwarz_axl.h"

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

// BEGIN_LINEARALGEBRA2SERVICE_NAMESPACE

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

class PETScPrecConfigAdditiveSchwarzService :
  public ArcanePETScPrecConfigAdditiveSchwarzObject
{
public:
  /** Constructeur de la classe */
  PETScPrecConfigAdditiveSchwarzService(const Arcane::ServiceBuildInfo & sbi) : 
    ArcanePETScPrecConfigAdditiveSchwarzObject(sbi) 
    {
      ;
    }
  
  /** Destructeur de la classe */
  virtual ~PETScPrecConfigAdditiveSchwarzService() {}
  
public:

  //! Initialisation
  void configure(PC & pc, const Alien::IIndexManager * indexManager);

  //! Indicateur de support de résolution parallèle
  bool hasParallelSupport() const;

  //! Check need of KSPSetUp before calling this PC configure
  virtual bool needPrematureKSPSetUp() const;

public:
  //! Acces to TraceMng
  ITraceMng * traceMng() const { return BasicService::traceMng();  }
};

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

void 
PETScPrecConfigAdditiveSchwarzService::
configure(PC & pc, const Alien::IIndexManager * indexManager)
{
  checkError("Set preconditioner",PCSetType(pc,PCASM));
  // KSPSetUp has been already called (cf needPrematureKSPSetUp)
  // you can set up sub solver using PCASMGetSubKSP
  // details in http://www-unix.mcs.anl.gov/petsc/petsc-as/snapshots/petsc-current/src/ksp/ksp/examples/tutorials/ex8.c.html

  if (options()->overlap() > 0)
    checkError("Set AdditiveSchwarz overlap",PCASMSetOverlap(pc,options()->overlap()));
  else
    fatal() << "AdditiveSchwarz does not allow non-positive overlapping";

  if (options()->localBlocks() <= 0)
    fatal() << "AdditiveSchwarz does not allow non-positive local blocks number";
  else if (options()->localBlocks() > 1)
    {
      checkError("Set AdditiveSchwarz blocks",PCASMSetLocalSubdomains(pc,options()->localBlocks(), PETSC_NULL, PETSC_NULL));
    }
  // else 1 : default

  switch (options()->type()) {
  case PETScPrecConfigAdditiveSchwarzOptionTypes::Basic:
    checkError("Set AdditiveSchwarz type",PCASMSetType(pc,PC_ASM_BASIC));
    break;
  case PETScPrecConfigAdditiveSchwarzOptionTypes::Restrict:
    checkError("Set AdditiveSchwarz type",PCASMSetType(pc,PC_ASM_RESTRICT));
    break;
  case PETScPrecConfigAdditiveSchwarzOptionTypes::Interpolate:
    checkError("Set AdditiveSchwarz type",PCASMSetType(pc,PC_ASM_INTERPOLATE));
    break;
  case PETScPrecConfigAdditiveSchwarzOptionTypes::None:
    checkError("Set AdditiveSchwarz type",PCASMSetType(pc,PC_ASM_NONE));
    break;
  default:
    throw InternalErrorException(A_FUNCINFO,"Undefined AdditiveSchwarz type");
  }

  checkError("Preconditioner setup",PCSetUp(pc));
  
  // Extract the array of KSP contexts for the local blocks
  PetscInt nlocal, first;
  KSP *subksp;
  checkError("Preconditioner gets sub-solvers",PCASMGetSubKSP(pc, &nlocal, &first, &subksp));

  for (Integer i=first; i<nlocal; i++) {
    options()->subSolver()->configure(subksp[i],NULL);
  }
}

/*---------------------------------------------------------------------------*/

bool
PETScPrecConfigAdditiveSchwarzService::
hasParallelSupport() const
{
  return options()->subSolver()->hasParallelSupport();
}

/*---------------------------------------------------------------------------*/

bool
PETScPrecConfigAdditiveSchwarzService::
needPrematureKSPSetUp() const
{
  return true;
}

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

ARCANE_REGISTER_SERVICE_PETSCPRECCONFIGADDITIVESCHWARZ(AdditiveSchwarz,PETScPrecConfigAdditiveSchwarzService);

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

// END_LINEARALGEBRA2SERVICE_NAMESPACE

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

