// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2025 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
#ifndef ARCGEOSIM_EXPRESSIONS_WEXPRESSIONMNGSERVICE_H
#define ARCGEOSIM_EXPRESSIONS_WEXPRESSIONMNGSERVICE_H
/* Author : faneyt at Wed Apr  2 17:10:10 2014
 * Generated by createNew
 */

#include "IWExpressionMng.h"
#include "ExpressionBuilder/LocalExpressionMng.h"

namespace Arcane { }
using namespace Arcane;

#include "WExpressionMng_axl.h"

#include <map>

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

class WExpressionMngService :
	public ArcaneWExpressionMngObject,
	public LocalExpressionMng
{
public:
  
  WExpressionMngService(const Arcane::ServiceBuildInfo & sbi) :
    ArcaneWExpressionMngObject(sbi)
    {
      ;
    }
  ~WExpressionMngService() {}
  
public:

  void init();

};

#endif /* ARCGEOSIM_EXPRESSIONS_WEXPRESSIONMNGSERVICE_H */
