// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2025 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
// -*- C++ -*-
#ifndef ARCGEOSIM_ARCGEOSIM_PHYSICS_LAW_FUNCTIONTRAITS_H
#define ARCGEOSIM_ARCGEOSIM_PHYSICS_LAW_FUNCTIONTRAITS_H
/* Author : desrozis at Tue Nov  6 12:32:59 2012
 * Generated by createNew
 */

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

BEGIN_LAW_NAMESPACE

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

namespace details {

  // TO DO : Checker la signature utilisateur
  
  template <typename T>
  class is_valid_function
  {
    typedef char one;
    typedef long two;
    template <typename C> static one test( typeof(&C::eval) ) ;
    template <typename C> static two test(...);
  public:
    enum { value = sizeof(test<T>(0)) == sizeof(char) };
  };
  
  template <typename T>
  class is_differentiable_function
  {
    typedef char one;
    typedef long two;
    template <typename C> static one test( typeof(&C::eval) ) ;
    template <typename C> static two test(...);
  public:
    enum { value = sizeof(test<T>(0)) == sizeof(char) };
  };

}

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

template<typename T>
struct FunctionTraits
{
  enum { is_valid = details::is_valid_function<T>::value };
  enum { is_differentiable = details::is_differentiable_function<T>::value };
};

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

END_LAW_NAMESPACE

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#endif /* ARCGEOSIM_ARCGEOSIM_PHYSICS_LAW_FUNCTIONTRAITS_H */
