def build_solver_dictionnary(solver_dict):
    solver_dict['HypreSolver']['max-it'] = 'num-iterations-max'
    solver_dict['HypreSolver']['tol'] = 'stop-criteria-value'
    solver_dict['HypreSolver']['solver'] = 'solver'
    solver_dict['HypreSolver']['solver-type'] = 'HypreOptionTypes::eSolver'
    solver_dict['HypreSolver']['precond'] = 'preconditioner'
    solver_dict['HypreSolver']['precond-type'] = 'HypreOptionTypes::ePreconditioner'
    solver_dict['HypreSolver']['verbose'] = 'verbose'

    solver_dict['PETScSolver']['max-it'] = 'num-iterations-max'
    solver_dict['PETScSolver']['tol'] = 'stop-criteria-value'
    solver_dict['PETScSolver']['solver'] = 'solver'
    solver_dict['PETScSolver']['precond'] = 'preconditioner'
    solver_dict['PETScSolver']['verbose'] = 'verbose'

    solver_dict['MTLSolver']['max-it'] = 'max-iteration-num'
    solver_dict['MTLSolver']['tol'] = 'stop-criteria-value'
    solver_dict['MTLSolver']['solver'] = 'solver'
    solver_dict['MTLSolver']['solver-type'] = 'MTLOptionTypes::eSolver'
    solver_dict['MTLSolver']['precond'] = 'preconditioner'
    solver_dict['MTLSolver']['precond-type'] = 'MTLOptionTypes::ePreconditioner'
    solver_dict['MTLSolver']['verbose'] = 'verbose'

    solver_dict['HTSSolver']['max-it'] = 'max-iteration-num'
    solver_dict['HTSSolver']['tol'] = 'stop-criteria-value'
    solver_dict['HTSSolver']['solver'] = 'solver'
    solver_dict['HTSSolver']['solver-type'] = 'HTSOptionTypes::eSolver'
    solver_dict['HTSSolver']['precond'] = 'preconditioner'
    solver_dict['HTSSolver']['precond-type'] = 'HTSOptionTypes::ePreconditioner'
    solver_dict['HTSSolver']['verbose'] = 'verbose'

    solver_dict['IFPSolver']['max-it'] = 'num-iterations-max'
    solver_dict['IFPSolver']['tol'] = 'stop-criteria-value'
    solver_dict['IFPSolver']['precond'] = 'precond-option'
    solver_dict['IFPSolver']['precond-type'] = 'IFPSolverProperty::ePrecondType'
    solver_dict['IFPSolver']['verbose'] = 'verbose'

    solver_dict['MCGSolver']['max-it'] = 'max-iteration-num'
    solver_dict['MCGSolver']['tol'] = 'stop-criteria-value'
    solver_dict['MCGSolver']['solver'] = 'solver'
    solver_dict['MCGSolver']['solver-type'] = 'MCGSolver::LinearSolver::eKrylovType'
    solver_dict['MCGSolver']['precond'] = 'preconditioner'
    solver_dict['MCGSolver']['precond-type'] = 'MCGSolver::ePrecondType'
    solver_dict['MCGSolver']['verbose'] = 'output'

    solver_dict['TrilinosSolver']['max-it'] = 'max-iteration-num'
    solver_dict['TrilinosSolver']['tol'] = 'stop-criteria-value'
    solver_dict['TrilinosSolver']['solver'] = 'solver'
    solver_dict['TrilinosSolver']['solver-type'] = 'TrilinosOptionTypes::eSolver'
    solver_dict['TrilinosSolver']['precond'] = 'preconditioner'
    solver_dict['TrilinosSolver']['precond-type'] = 'TrilinosOptionTypes::ePreconditioner'
    solver_dict['TrilinosSolver']['verbose'] = 'verbose'

#    solver_dict['HPDDMSolver']['max-it'] = 'max-iteration-num'
#    solver_dict['HPDDMSolver']['tol'] = 'stop-criteria-value'
#    solver_dict['HPDDMSolver']['solver'] = 'krylov-method'
#    solver_dict['HPDDMSolver']['solver-type'] = 'string'
#    solver_dict['HPDDMSolver']['verbose'] = 'verbose'
