// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2025 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
#ifndef COORESARCANE_WORK_REACTIVETRANSPORT_REACTIVETRANSPORTBOUNDARYCONDITIONMNG_IBOUNDARYCONDITION_H
#define COORESARCANE_WORK_REACTIVETRANSPORT_REACTIVETRANSPORTBOUNDARYCONDITIONMNG_IBOUNDARYCONDITION_H
/* Author : dipietrd at Tue Jun 24 09:13:24 2008
 * Generated by createNew
 */

#include <arcane/VariableTypes.h>

using namespace Arcane;

class IBoundaryCondition {
 public:
  virtual ~IBoundaryCondition() {}

  //! Return boundary condition type    
  virtual Integer getType() = 0;
};

#endif /* COORESARCANE_WORK_REACTIVETRANSPORT_REACTIVETRANSPORTBOUNDARYCONDITIONMNG_IBOUNDARYCONDITION_H */
