#ifndef ARCGEOSIM_NUMERICS_EXPRESSIONS_LINEARPIECEWISEFUNCTIONSERVICE_H
#define ARCGEOSIM_NUMERICS_EXPRESSIONS_LINEARPIECEWISEFUNCTIONSERVICE_H
/* Author : dechaiss at Wed Oct 14 10:22:34 2009
 * Generated by createNew
 */

// Interface du service 
#include "ArcGeoSim/Numerics/Expressions/IFunctionR1vR1.h"
#include "ArcGeoSim/Numerics/Expressions/PieceWiseFunction/PieceWiseFunctionR1vR1.h"
#include "ArcGeoSim/Numerics/Expressions/PieceWiseFunction/LinearPieceWiseFunction/LinearInterpolator.h"

namespace Arcane
  {
  }
using namespace Arcane;

#include "LinearPieceWiseFunction_axl.h"

class LinearPieceWiseFunctionService : public ArcaneLinearPieceWiseFunctionObject,
    public PieceWiseFunctionR1vR1T<LinearInterpolator>
  {
public:
  /** Constructeur de la classe */
  LinearPieceWiseFunctionService(const Arcane::ServiceBuildInfo & sbi) :
    ArcaneLinearPieceWiseFunctionObject(sbi), PieceWiseFunctionR1vR1T<
        LinearInterpolator> (traceMng()), m_initialized(false)
    {
      ;
    }

  /** Destructeur de la classe */
  virtual
  ~LinearPieceWiseFunctionService()
    {
    }

public:

  //! Initialisation
  void
  init();

private:
  bool m_initialized;
  };

#endif /* ARCGEOSIM_NUMERICS_EXPRESSIONS_LINEARPIECEWISEFUNCTIONSERVICE_H */
