#include "ColumnPartitionConstraint.h"
/* Author : delhombr at Fri Oct 26 11:41:30 2018
 * Generated by createNew
 */


/*---------------------------------------------------------------------------*/

ColumnPartitionConstraint::
#if (ARCANE_VERSION >= 30003)
ColumnPartitionConstraint(Arcane::IMesh* mesh, Arcane::IGraph2* graph,
#else
ColumnPartitionConstraint(Arcane::IMesh* mesh,
#endif
                          ArcGeoSim::ItemConnectionGroup my_cell_cell_connections)
: m_mesh(mesh)
#if (ARCANE_VERSION >= 30003)
, m_graph(graph)
#endif
, m_my_cell_cell_connections(my_cell_cell_connections)
{
	//fill linked_cells & owners
//	item->owner()
	  ENUMERATE_CONNECTION(iconnection,m_my_cell_cell_connections)
	  {
	    ArcGeoSim::ItemConnection connection = *iconnection;
#if (ARCANE_VERSION >= 30003)
            const Arcane::Item& first_item = connection.first(m_graph);
            const Arcane::Item& second_item = iconnection->second(m_graph);
#else
	    const Arcane::Item& first_item = connection.first();
	    const Arcane::Item& second_item = iconnection->second();
#endif
	    //std::cout<< "Connection uid from enum " << iconnection->uniqueId().asInt64();
	    //std::cout<< "Connection uid from connection " << connection.uniqueId().asInt64();
	    std::cout<< "First item uid " << first_item.uniqueId().asInteger() << " Second item uid " << second_item.uniqueId().asInteger();
	    //std::cout<< "Connection type " << iconnection->type();
		m_linked_cells.add(first_item.uniqueId().asInteger());
		m_linked_cells.add(second_item.uniqueId().asInteger());
		m_linked_owners.add(first_item.owner());
	  }
}

/*---------------------------------------------------------------------------*/

void
ColumnPartitionConstraint::
addLinkedCells(Int64Array& linked_cells,Int32Array& linked_owners)
{
	linked_cells.addRange(m_linked_cells);
	linked_owners.addRange(m_linked_owners);

}

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/
