#ifndef ARCGEOSIM_TESTS_FIELDSERVICEVALIDATOR_ARRAYVARIABLEACCESSOR_ARRAYVARIABLEACCESSORSERVICE_H
#define ARCGEOSIM_TESTS_FIELDSERVICEVALIDATOR_ARRAYVARIABLEACCESSOR_ARRAYVARIABLEACCESSORSERVICE_H
/* Author : dechaiss at Wed Aug 26 11:29:27 2009
 * Generated by createNew
 */
#include "ArcGeoSim/Tests/Utils/IDataAccessor.h"

namespace Arcane
{
}
using namespace Arcane;

#include "ArrayVariableAccessor_axl.h"
#include <arcane/IVariable.h>

class ArrayVariableAccessorService : public ArcaneArrayVariableAccessorObject
{
public:
  /** Constructeur de la classe */
  ArrayVariableAccessorService(const Arcane::ServiceBuildInfo & sbi) 
    : ArcaneArrayVariableAccessorObject(sbi)
    , m_initialized(false)
    , m_ivariable(NULL)
  {
    ;
  }

  /** Destructeur de la classe */
  virtual
  ~ArrayVariableAccessorService() {}

public:

  //! Initialisation
  void init(const ItemGroup& group);

  //! Apply service function
  IVariable* variable(const ItemGroup& group);

private:

  bool m_initialized;

  //! Variable data
  IVariable * m_ivariable;

};

#endif /* ARCGEOSIM_TESTS_FIELDSERVICEVALIDATOR_ARRAYVARIABLEACCESSOR_ARRAYVARIABLEACCESSORSERVICE_H */
