// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2025 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
#ifndef ARCGEOSIM_SURFACEUTILS_INOTMATCHINGSURFACEBUILDER_H
#define ARCGEOSIM_SURFACEUTILS_INOTMATCHINGSURFACEBUILDER_H
/* Author : havep at Tue Sep  1 12:00:58 2009
 * Generated by createNew
 */
#include "ArcGeoSim/Utils/ArcGeoSim.h"

BEGIN_ARCGEOSIM_NAMESPACE
BEGIN_SURFACE_NAMESPACE

// Pr�-d�claration
class INotMatchingSurfaceMngAccessor;

//! Calculateur d�port� pour les calculs de non-conformit�s.
class INotMatchingSurfaceBuilder
{
public:
  //! Destructeur de la classe
  virtual ~INotMatchingSurfaceBuilder() { }
  
public:

  //! Initialisation
  virtual void init() = 0;

  //! Ajout d'une propri�t�
  /*! Permet les d�clenchements associ�s; ne constitue pas un stockage de l'information */
  virtual void addPropertiesTrigger(const Integer property) = 0;

  //! Apply service function
  virtual void update(INotMatchingSurfaceMngAccessor * access) = 0;
};


END_SURFACE_NAMESPACE
END_ARCGEOSIM_NAMESPACE

#endif /* ARCGEOSIM_SURFACEUTILS_INOTMATCHINGSURFACEBUIDER_H */
