// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2022 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
#ifndef ILAWCONFIG_H
#define ILAWCONFIG_H
/* Author : desrozis at Tue Dec 15 07:26:34 2009
 * Generated by createNew
 */

#include "DiPhasicTest/Physics/Properties.h"

#include "ArcGeoSim/Physics/Law2/FunctionManager.h"

class Support;

class ILawConfig
{
public:
  virtual ~ILawConfig() {}
public:
  virtual void initialize(const Law::ScalarRealProperty& p, Law::FunctionManager& law_register) = 0;
};

#endif /* ILAWCONFIG_H */
