// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2025 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
// -*- C++ -*-
#ifndef ARCGEOSIM_ARCGEOSIM_PHYSICS_LAW_PROPERTY_H
#define ARCGEOSIM_ARCGEOSIM_PHYSICS_LAW_PROPERTY_H
/* Author : desrozis at Tue Oct 30 16:51:25 2012
 * Generated by createNew
 */

/*
 * \ingroup Law
 * \brief Propri�t�s physiques utilis�es dans les outils lois.
 *
 * D�crit une propri�t� physique ayant :
 *   - un identifiant unique (� la charge de l'utilisateur)
 *   - un nom unique (� la charge de l'utilisateur)
 *   - une dimension (scalaire ou vectorielle)
 *   - une taille (1 en scalaire et fournie par l'utilisateur en vectoriel)
 *   - un type de donn�e
 *
 * \code
 * ScalarRealProperty pressure(0,"Pressure");
 * VectorialRealProperty saturation(1,"Saturation",2); // taille 2
 * VectorialRealProperty composition(2,"Composition");
 * composition.initialize(3);
 * \endcode
 *
 * ATTENTION : il convient de d�finir son mod�le de donn�es et de fixer les tailles
 * avant d'utiliser les outils lois
 *
 */

#include "ArcGeoSim/Physics/Gump/Property.h"
#include "ArcGeoSim/Physics/Law2/Dimension.h"

#include <arcane/utils/ValueConvert.h>
#include <arcane/VariableDataTypeTraits.h>

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

BEGIN_LAW_NAMESPACE

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

/*!
 * \brief Classe g�n�rique de propri�t� 
 *
 * Utilis�e pour le stockage
 *
 */
class Property
{
public:
  
  Property()
    : m_id(-1)
    , m_name("Unknown")
    , m_dim(eUndefined)
    , m_data_type(Arcane::DT_Unknown)
    , m_size(0) {} // Pour �tre dans conteneurs STL ou Arcane
  
  virtual ~Property() {}

protected: 

  Property(Integer id, 
           const String& name,
           Dimension dim, 
           Arcane::eDataType data_type,
           Integer size)
    : m_id(id)
    , m_name(name)
    , m_dim(dim)
    , m_data_type(data_type)
    , m_size(size) 
  {
    if(id < 0) throw Arcane::FatalErrorException("Property construction error : id < 0");
  }
 
public:
  
  //! Initialisation de la propri�t� (pour vectoriel)
  void initialize(Integer size) 
  {
    ARCANE_ASSERT((m_dim == eVectorial),("Scalar property mustn't be initialized"));
    if(m_size > 0) 
      throw Arcane::FatalErrorException("Property is already initialized");
    m_size = size;
  }

  //! Dimension de la propri�t�
  Dimension dimension() const { return m_dim; } 
  
  //! Type des donn�es
  Arcane::eDataType dataType() const { return m_data_type; }
 
  //! Identifiant de la propri�t�
  Integer id() const { return m_id; }
  
  //! Name de la propri�t�
  const String& name() const { return m_name; }
  
  //! Taille de la propri�t�s 
  // ie 1 en scalaire, la taille du vecteur en vectoriel
  Integer size() const { return m_size; }

  //! Comparaison pour �tre dans conteneurs tri�s STL
  bool operator<(const Property& p) const { return m_id < p.m_id; }

  //! Comparaison pour �tre dans conteneurs tri�s STL
  bool operator!=(const Property& p) const { return m_id != p.m_id; }

  //! Teste si la propri�t� est d�finie
  bool isInitialized() const { return m_id >= 0 && m_size > 0; }

private:
  
  Integer m_id; 
  String m_name;
  Dimension m_dim;
  Arcane::eDataType m_data_type;

protected:
  
  bool m_is_parameter;
  Integer m_size;
};

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

/*!
 * \brief Classe statique de propri�t� 
 *
 */
template<Dimension, typename> class PropertyT; 

/*!
 * \brief Propri�t� scalaire
 *
 */
template<typename T>
class PropertyT<eScalar,T> : public Property
{
public:
  
  PropertyT() {} // Pour �tre dans les vecteurs fusions

  // Pour le static_cast
  PropertyT(const Property& prop)
   : Property(prop.id(), prop.name(), eScalar, Arcane::VariableDataTypeTraitsT<T>::type(), 1){}

  PropertyT(Integer id, const String& name)
    : Property(id, name, eScalar, Arcane::VariableDataTypeTraitsT<T>::type(), 1) {}

  template<typename P>
  PropertyT(const P& prop)
  : PropertyT(prop.uniqueId(),prop.fullName())
  {}
};

/*!
 * \brief Propri�t� vectorielle
 *
 */
template<typename T>
class PropertyT<eVectorial,T> : public Property
{
public:
  
  PropertyT() {} // Pour �tre dans les vecteurs fusions
  
  // Pour le static_cast
  PropertyT(const Property& prop)
     : Property(prop.id(), prop.name(), eVectorial, Arcane::VariableDataTypeTraitsT<T>::type(), prop.size()){}

  PropertyT(Integer id, String name, Integer size = 0)
    : Property(id, name, eVectorial, Arcane::VariableDataTypeTraitsT<T>::type(), size) {}

};

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

// Types utilisateurs

typedef PropertyT<eScalar   ,Real   >       ScalarRealProperty;
typedef PropertyT<eVectorial,Real   >    VectorialRealProperty;
typedef PropertyT<eScalar   ,Integer>    ScalarIntegerProperty;
typedef PropertyT<eVectorial,Integer> VectorialIntegerProperty;
typedef PropertyT<eScalar   ,Byte   >    ScalarBooleanProperty;
typedef PropertyT<eVectorial,Byte   > VectorialBooleanProperty;

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/
// Pour le debug

inline std::ostream& operator<<(std::ostream& nout, const Property& p)
{
  nout << "Property '" << p.name() 
       << "' {id=" << p.id() 
       << ",dim='" << p.dimension() 
       << "',type='" << p.dataType() 
       << "'}";
  if(p.dimension() == eVectorial)
    nout << "[size=" << p.size() << "]";
  
  return nout;
}

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

END_LAW_NAMESPACE

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#endif /* ARCGEOSIM_ARCGEOSIM_PHYSICS_LAW_PROPERTY_H */
