// -*- C++ -*-
#ifndef LAW_CONTRIBUTION_VARIABLEARRAY_H
#define LAW_CONTRIBUTION_VARIABLEARRAY_H
/* Author : desrozis at Tue Nov 13 08:40:09 2012
 * Generated by createNew
 */

#include "ArcGeoSim/Physics/Law2/Variable.h"
#include "ArcGeoSim/Physics/Law2/VariableRef.h"

#include "ArcGeoSim/Numerics/Contribution/Variable/VariableArray.h"

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

BEGIN_LAW_NAMESPACE
BEGIN_AUDI_NAMESPACE

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

class VariableArray
    : public Law::VariableT< Law::ArrayRefT<Law::ScalarRealProperty> >
    , private ArcNum::audi::VariableArray
{
public:

  typedef Law::VariableT< Law::ArrayRefT<Law::ScalarRealProperty> > Base;
  typedef ArcNum::audi::VariableArray                               AuDiBase ;

  VariableArray() {}

  VariableArray(const VariableArray& rhs)
  : Base(rhs)
  , AuDiBase(rhs) {}

  VariableArray(const Law::BuildInfo<Law::ScalarRealProperty>& bi)
  : Base(bi.property(), bi.offsets(), bi.variableMng().arrays())
  , AuDiBase(bi.offsets().constView())
  {
    auto const& property = bi.property() ;
    auto const& accessor = bi.variableMng().arrays() ;
    AuDiBase::setValues(&(accessor.values(property))) ;
    if(accessor.hasDerivatives(property))
      AuDiBase::setDerivValues(&(accessor.derivatives(property))) ;
  }

  virtual ~VariableArray() {}

public:
  
  inline const ArcNum::RootContribution& operator[](Arcane::Integer item) const
  {
    return AuDiBase::operator[](item) ;
  }

  inline const ArcNum::RootContribution& operator[](const ArcNum::Stencil::IntegerIndex& item) const
  {
    return AuDiBase::operator[](item) ;
  }

private:
};
/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

END_LAW_NAMESPACE
END_AUDI_NAMESPACE

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/

#endif /* LAW_CONTRIBUTION_VARIABLEARRAY_H */
