#ifndef ARCGEOSIM_TESTS_SERVICETESTERS_MESHGENERATORTESTER_MESHGENERATORSERVICE_H
#define ARCGEOSIM_TESTS_SERVICETESTERS_MESHGENERATORTESTER_MESHGENERATORSERVICE_H
/* Author : gratienj at Fri Mar 20 15:15:30 2009
 * Generated by createNew
 */

#include "ArcGeoSim/Tests/ServiceTesters/IServiceTester.h"

namespace Arcane { }
using namespace Arcane;

#include "ArcGeoSim/Mesh/Generator/IMeshGenerator.h"
#include "MeshGeneratorTester_axl.h"

class MeshGeneratorTesterService :
  public ArcaneMeshGeneratorTesterObject
{
public:
  /** Constructeur de la classe */
  MeshGeneratorTesterService(const Arcane::ServiceBuildInfo & sbi) : 
    ArcaneMeshGeneratorTesterObject(sbi),
    m_generator(NULL)
    {
      ;
    }
  
  /** Destructeur de la classe */
  virtual ~MeshGeneratorTesterService() {}
  
public:

  //! Initialization
  void init();
  //! Run the test
  int test();
private :
  IMeshGenerator* m_generator ;
};

#endif /* ARCGEOSIM_TESTS_SERVICETESTERS_MESHGENERATORTESTER_MESHGENERATORSERVICE_H */
