#ifndef ARCGEOSIM_NUMERICS_EXPRESSIONS_CONSTANTPIECEWISEFUNCTION_CONSTANTPIECEWISEFUNCTIONSERVICE_H
#define ARCGEOSIM_NUMERICS_EXPRESSIONS_CONSTANTPIECEWISEFUNCTION_CONSTANTPIECEWISEFUNCTIONSERVICE_H
/* Author : dechaiss at Mon Oct 19 15:53:58 2009
 * Generated by createNew
 */

// Interface du service 
#include "ArcGeoSim/Numerics/Expressions/IFunctionR1vR1.h"
#include "ArcGeoSim/Numerics/Expressions/PieceWiseFunction/PieceWiseFunctionR1vR1.h"
#include "ConstantInterpolator.h"

namespace Arcane
  {
  }
using namespace Arcane;

#include "ConstantPieceWiseFunction_axl.h"

class ConstantPieceWiseFunctionService : 
    public ArcaneConstantPieceWiseFunctionObject,
    public PieceWiseFunctionR1vR1T<ConstantInterpolator>
  {
public:
  /** Constructeur de la classe */
  ConstantPieceWiseFunctionService(const Arcane::ServiceBuildInfo & sbi) :
    ArcaneConstantPieceWiseFunctionObject(sbi), PieceWiseFunctionR1vR1T<
    ConstantInterpolator> (traceMng()), m_initialized(false)
    {
      ;
    }

  /** Destructeur de la classe */
  virtual
  ~ConstantPieceWiseFunctionService()
    {
    }

public:

  //! Initialisation
  void
  init();
  
private:
  bool m_initialized;

  };

#endif /* ARCGEOSIM_NUMERICS_EXPRESSIONS_CONSTANTPIECEWISEFUNCTION_CONSTANTPIECEWISEFUNCTIONSERVICE_H */
