#ifndef ARCGEOSIM_NUMERICS_EXPRESSIONS_CONSTANTFUNCTION_CONSTANTFUNCTION_H
#define ARCGEOSIM_NUMERICS_EXPRESSIONS_CONSTANTFUNCTION_CONSTANTFUNCTION_H
/* Author : desrozis at Mon Feb 16 17:26:13 2009
 * Generated by createNew
 */

namespace Arcane
  {
  }
using namespace Arcane;

#include "ArcGeoSim/Numerics/Expressions/IFunctionR1vR1.h"

#include <arcane/ArcaneVersion.h>
#include <arcane/utils/Array.h>
#include <arcane/utils/String.h>
#include <arcane/utils/ITraceMng.h>

class ConstantFunction : public IFunctionR1vR1
  {
public:
  /** Constructeur de la classe */
  ConstantFunction(ITraceMng * trace_mng) :
    m_trace_mng(trace_mng)
    {
      ;
    }

  /** Destructeur de la classe */
  virtual
  ~ConstantFunction()
    {
    }

public:

  //@{ @name Methods from IIFunction

  //! Initialisation
  void
  init();

  //! Setting parameter
  void
  setParameter(const String & name, const Real & parameter);
  void
  setParameter(Integer index, const Real & parameter);

  //! Getting number of parameter
  Integer
  nbParameter() const;

  //! Getting name of parameter
  String
  parameterName(Integer index) const;

  //! Setting vectorized variable
  void
  setVariable(const String & name, const Array<Real> & variable);
  void
  setVariable(Integer index, const Array<Real> & variable);

  //! Getting number of variable
  Integer
  nbVariable() const;

  //! Getting name of variable
  String
  variableName(Integer index) const;

  //! Setting evaluation vectorized result
  void
  setEvaluationResult(Array<Real> & result);

  //! Setting derivation vectorized result
  /*! Derivation following @name di variable */
  void
  setDerivationResult(Integer di, Array<Real> & result);

  //! Setting derivation vectorized result
  /*! Derivation following @name di variable */
  void
  setDerivationResult(const String & di, Array<Real> & result);

  //! Eval vectorized data service function
  void
  eval();

  //! Cleanup
  void
  cleanup();

  //@}

public:

  //@{ @name Local methods

  //! Point-wise evaluation
  Real
  eval(const Real & var0);
  void
  eval(const Real & var0, Real & res0);

  //! Vector evaluation
  void
    eval(const Array<Real> & var0, Array<Real> & res0);

  //! Vector evaluation
  void
  eval(const ConstArrayView<Real> var0, ArrayView<Real> res0);

  //! Coupled function and derivative scalar evaluation (temporary: derivation handling in IFunction still to be defined)
  void
  eval(const Real & var0, Real & res0, Real & diffres0)
    {
      m_trace_mng->fatal() << "Not yet implemented";
    }

  //! Point-wise derivation (temporary: derivation handling in IFunction still to be defined)
  Real
  diffEval(const Real & variable)
    {
      m_trace_mng->fatal() << "Not yet implemented";
      return 0;
    }

  //@}

public:

  //! Setting name of variable
  void
  setVariableName(const String & name);

  //! Setting constant value
  void
  setConstant(const Real & value);

protected:
  //! Trace manager
  ITraceMng * m_trace_mng;

  //! Variable name
  String m_name;

  // Constant value
  Real m_value;

  RealArrayView m_eval_result;
  RealArrayView m_diff_result;
  };

#endif /* ARCGEOSIM_NUMERICS_EXPRESSIONS_CONSTANTFUNCTION_CONSTANTFUNCTION_H */
