#include "IXMMeshFile.h"
/* Author : dechaiss at Thu Oct 11 10:49:31 2012
 * Generated by createNew
 */

#include <arcane/utils/FatalErrorException.h>
#include <arcane/IParallelMng.h>
#include <arcane/XmlNode.h>
#include <arcane/XmlNodeList.h>
#include <arcane/IXmlDocumentHolder.h>
#include <arcane/utils/PlatformUtils.h>

/*---------------------------------------------------------------------------*/

Arcane::IXmlDocumentHolder*
operator<<(Arcane::IXmlDocumentHolder* & xml_doc, const ArcGeoSim::IXMMeshFile& mesh_file)
{
  xml_doc = mesh_file();
  return xml_doc;
}

/*---------------------------------------------------------------------------*/
/* Class IXMMeshVersion                                                      */
/*---------------------------------------------------------------------------*/

/*---------------------------------------------------------------------------*/

ArcGeoSim::IXMMeshVersion::
IXMMeshVersion()
 : internal_version(ArcGeoSim::UndefinedIXMVersion)
 , internal_string("UndefinedIXMVersion")
{}

/*---------------------------------------------------------------------------*/

ArcGeoSim::IXMMeshVersion::
IXMMeshVersion(const eIXMMeshVersion& mesh_version)
 : internal_version(mesh_version)
{
  _versionFromEnum(mesh_version);
}

/*---------------------------------------------------------------------------*/

ArcGeoSim::IXMMeshVersion::
IXMMeshVersion(const Arcane::String& mesh_version)
 : internal_string(mesh_version)
{
  _versionFromString(mesh_version);
}

/*---------------------------------------------------------------------------*/

bool
ArcGeoSim::IXMMeshVersion::
operator== (const IXMMeshVersion& mesh_version) const
{
  if ((mesh_version.internal_version != internal_version) && (mesh_version.internal_string != internal_string)) return false;
  else return true;
}


/*---------------------------------------------------------------------------*/

void
ArcGeoSim::IXMMeshVersion::
_versionFromString(const Arcane::String& version)
{
  if (version == "V3") internal_version = ArcGeoSim::IXMV3;
  else if (version == "V4") internal_version = ArcGeoSim::IXMV4;
  else if (version == "V4_1_0") internal_version = ArcGeoSim::IXMV4_1_0;
  else internal_version = ArcGeoSim::UndefinedIXMVersion;
}

/*---------------------------------------------------------------------------*/

void
ArcGeoSim::IXMMeshVersion::
_versionFromEnum(const eIXMMeshVersion& version)
{
  switch (version) {
  case ArcGeoSim::IXMV3:
    internal_string = "V3";
    break;
  case ArcGeoSim::IXMV4:
    internal_string = "V4";
    break;
  case ArcGeoSim::UndefinedIXMVersion:
    internal_string = "UndefinedIXMVersion";
    break;
  }
}

/*---------------------------------------------------------------------------*/
/* Class IXMMeshFile                                                         */
/*---------------------------------------------------------------------------*/

ArcGeoSim::IXMMeshFile::
IXMMeshFile(const Arcane::String& filename)
 : m_filename(filename)
 , m_xml_doc(NULL)
 , m_mesh_version(ArcGeoSim::UndefinedIXMVersion)
{}

/*---------------------------------------------------------------------------*/

ArcGeoSim::IXMMeshVersion
ArcGeoSim::IXMMeshFile::
version(Arcane::IIOMng* io_mng,Arcane::IParallelMng* parallel_mng)
{
  if (m_mesh_version() == ArcGeoSim::UndefinedIXMVersion)
    {
      // Get file version : standard = root node has a "version" attribute
      // Read without any scheme only to get version. This pre-reading is needed to select the appropriate mesh reader (knowing the version).
      if(parallel_mng->commRank()==0)
      {
        Arcane::ByteSharedArray buffer;
        Integer error = io_mng->localRead(m_filename,buffer)?1:0 ;
        parallel_mng->broadcast(ArrayView<Integer>(1,&error),0) ;
        if(error==1)
          throw Arcane::FatalErrorException(String::format("Cannot read xml data file '{0}'",m_filename));

        Arcane::IXmlDocumentHolder* xml_doc =  io_mng->parseXmlBuffer(buffer,"pre-reading");

        // Get version attribute
        Arcane::XmlNodeList root_child = xml_doc->documentNode().children();
        if (root_child.size() != 1) throw Arcane::FatalErrorException("Unknown IXM file structure (more than one mesh root node). Cannot determine version.");
        Arcane::String version = root_child[0].attrValue("version");

        // IXM V3 peculiarity : version is not mandatory
        if (version.empty())
        {
             m_mesh_version = ArcGeoSim::IXMMeshVersion(ArcGeoSim::IXMV3);
             version = "V3";
        }
        else m_mesh_version = version;

        parallel_mng->broadcastString(version,0) ;
        delete xml_doc;
      }
      else
      {
        Integer error ;
        parallel_mng->broadcast(ArrayView<Integer>(1,&error),0) ;
        if(error==1)
          throw Arcane::FatalErrorException(String::format("Cannot read xml data file '{0}'",m_filename));

        String version ;
        parallel_mng->broadcastString(version,0) ;
        m_mesh_version = version;
      }
    }
  return m_mesh_version;
}

/*---------------------------------------------------------------------------*/

ArcGeoSim::IXMMeshFile&
ArcGeoSim::IXMMeshFile::
operator() (Arcane::IIOMng* io_mng, const Arcane::String& schema_name,const Arcane::ByteConstArrayView schema_data)
{
  m_xml_doc = io_mng->parseXmlFile(m_filename, schema_name,schema_data);

//#ifndef NO_USER_WARNING
//#ifndef WIN32
//#warning "TODO: Eviter la lecture multiple parall���le du fichier racine du maillage"
//#endif
//#endif
  if (m_xml_doc == NULL) 
          throw Arcane::FatalErrorException(String::format("Cannot read xml data file '{0}'",m_filename));

  return *this;
 }

/*---------------------------------------------------------------------------*/

Arcane::String
ArcGeoSim::IXMMeshFile::
path()
{
  return Arcane::platform::getFileDirName(m_filename);
}

/*---------------------------------------------------------------------------*/


/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/
