// -*- tab-width: 2; indent-tabs-mode: nil; coding: utf-8-with-signature -*-
//-----------------------------------------------------------------------------
// Copyright 2000-2026 CEA (www.cea.fr) IFPEN (www.ifpenergiesnouvelles.com)
// See the top-level COPYRIGHT file for details.
// SPDX-License-Identifier: Apache-2.0
//-----------------------------------------------------------------------------
#include "IXMStaticMeshBuilder.h"
/* Author : dechaiss at Tue Oct 23 14:15:59 2012
 * Generated by createNew
 */

#include <arcane/IMeshSubMeshTransition.h>
#include <arcane/IPrimaryMesh.h>
#include <arcane/ISubDomain.h>

/*---------------------------------------------------------------------------*/

ArcGeoSim::IXMStaticMeshBuilder::
IXMStaticMeshBuilder(Arcane::ISubDomain* subdomain)
  : IXMMeshBuilderBase(subdomain->defaultMesh(),subdomain->traceMng(),subdomain->parallelMng(),IXMMeshType::StaticMesh)
{}

/*---------------------------------------------------------------------------*/

void
ArcGeoSim::IXMStaticMeshBuilder::
setDimension(Arcane::IPrimaryMesh* mesh, const ArcGeoSim::IXMTools::IXMMeshDimension mesh_dimension)
{
  IXMMeshBuilderBase::staticInit(mesh);
  mesh->setDimension(mesh_dimension());
}

/*---------------------------------------------------------------------------*/

void
ArcGeoSim::IXMStaticMeshBuilder::
addCells(Arcane::IPrimaryMesh* mesh, const ArcGeoSim::IXMTools::IXMCellData& cell_data)
{
  IXMMeshBuilderBase::manageCellOperations(mesh,cell_data,IXMCellData(),IXMCellData(),IXMCellIncrementPartitionInfo(),true);
}


void
ArcGeoSim::IXMStaticMeshBuilder::
setNodeCoordinates(Arcane::IPrimaryMesh* mesh, const ArcGeoSim::IXMTools::IXMNodeData& node_data)
{
  IXMMeshBuilderBase::manageUpdatedNodes(mesh,node_data,IXMClonedNodeData(),true);
}

void
ArcGeoSim::IXMStaticMeshBuilder::
addGroups(Arcane::IPrimaryMesh* mesh, const ArcGeoSim::IXMTools::IXMGroupDataList& group_data_list,const IXMUidToLidMng& uid2lid_mng)
{
  for (IXMGroupDataList::const_iterator ite = group_data_list.begin(); ite != group_data_list.end(); ++ite)
    {
      IXMMeshBuilderBase::manageGroup(mesh,*ite,"reset",uid2lid_mng,true);
    }
}

/*---------------------------------------------------------------------------*/
/*---------------------------------------------------------------------------*/
